# Generated by Django 6.0 on 2025-12-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Registro', models.IntegerField(blank=True, null=True, unique=True)),
                ('Correo', models.EmailField(max_length=150, unique=True)),
                ('Contrasena', models.CharField(max_length=255)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True)),
                ('Estado', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Logo', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goles_Local', models.IntegerField(default=0)),
                ('Goles_Visitante', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('IDUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deporte_bd.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('IDUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deporte_bd.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('IDCategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Fecha_Inicio', models.DateField(blank=True, null=True)),
                ('Fecha_Fin', models.DateField(blank=True, null=True)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('IDDeporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.deporte')),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCampeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDEquipo_Local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='deporte_bd.equipo')),
                ('IDEquipo_Visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='deporte_bd.equipo')),
                ('IDFixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.fixture')),
                ('IDInstalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.instalacion')),
                ('IDResultado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deporte_bd.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.IntegerField(blank=True, null=True)),
                ('Descripcion', models.TextField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IDPartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.partido')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='IDRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.rol'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='IDUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.delegado'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('IDUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deporte_bd.usuario')),
                ('Observacion', models.TextField(blank=True, null=True)),
                ('IDEquipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posicion', models.IntegerField(blank=True, null=True)),
                ('Puntos', models.IntegerField(blank=True, null=True)),
                ('IDCampeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.campeonato')),
                ('IDEquipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deporte_bd.equipo')),
            ],
            options={
                'verbose_name': 'Historial del Campeonato',
                'verbose_name_plural': 'Historiales de Campeonatos',
                'unique_together': {('IDCampeonato', 'IDEquipo')},
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDPermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.permiso')),
                ('IDRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.rol')),
            ],
            options={
                'verbose_name': 'Rol y Permiso',
                'verbose_name_plural': 'Roles y Permisos',
                'unique_together': {('IDRol', 'IDPermiso')},
            },
        ),
    ]
