# Generated by Django on 2025-12-05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deporte_bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Detalle', models.TextField(blank=True, null=True)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
            },
        ),
    ]
