# Generated by Django 6.0 on 2025-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte_bd', '0002_add_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='DG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='GC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='GF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='PE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='PG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='PJ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='PP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Puntos',
            field=models.IntegerField(default=0),
        ),
    ]
