# Generated by Django 6.0 on 2025-12-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte_bd', '0003_historial_dg_historial_gc_historial_gf_historial_pe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='Fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='Numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='IDCampeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte_bd.campeonato'),
        ),
    ]
