# Generated by Django 4.2.7 on 2025-10-23 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('jornada', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marcador', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('registro', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('estado', models.BooleanField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='core.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='core.equipo')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fixture')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instalacion')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='campeonato',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deporte'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='campeonato',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizador'),
        ),
    ]
