# Generated by Django 4.2.7 on 2025-10-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
