# Generated by Django 4.2.7 on 2025-10-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campeonato_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='categoria',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
            preserve_default=False,
        ),
    ]
