# Generated by Django 4.2.7 on 2025-10-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_deporte_categoria_campeonato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
